### ISSUE TITLE
[iOS] 디자인 잔여이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs#69]
[개선사항]

@somedd 재욱님 잔여이슈 전달드립니다!!!
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=2906-8381&t=Z6OI9XwLcM8JBHJX-1
[업체상세.pdf](https://github.com/user-attachments/files/16450958/default.pdf)
<img width="967" alt="업체상세@2x" src="https://github.com/user-attachments/assets/0f4dd41c-8ab0-4804-a63c-52113e7804dd">

**Comment by Dumbs-app** [comment]
@somedd 
재욱님 여기 이어서 전달드리겠습니다~!
[24.08.24. ios.pdf](https://github.com/user-attachments/files/16736347/24.08.24.ios.pdf)
<img width="967" alt="24 08 24  ios@2x" src="https://github.com/user-attachments/assets/4227ea79-142e-42c7-96c7-314485838c9a">
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3195-8445&t=HRFdNmZ0CqbHc1TK-1

**Comment by Dumbs-app** [comment]
<img width="590" alt="스크린샷 2024-08-24 오후 8 20 28" src="https://github.com/user-attachments/assets/9dfbdac6-e170-4485-a8a9-0c0f139c2496">

@somedd 
그리고 업체상세에서 이미지 비율 이슈도 한번 확인 부탁드리겠습니당!!!

**Comment by Dumbs-app** [comment]
@somedd 님
쿠폰레이어 관련 디자인이슈도 이어서 확인 부탁드리겠습니다!! ([figma](https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=3239-23089&t=8WYEhGrdGEEYdsPI-1))
[24.08.28. ios.pdf](https://github.com/user-attachments/files/16784734/24.08.28.ios.pdf)
<img width="933" alt="24 08 28  ios@2x" src="https://github.com/user-attachments/assets/682d7138-68b8-4d78-b69e-5cf6550e124b">

**유의사항 텍스트**
- 업체 상세페이지에서 운영시간과 유의사항 등을 반드시 확인한 후 사용하시기 바랍니다.
- 미성년자의 경우 입장 및 쿠폰 사용이 불가할 수 있습니다.
- 쿠폰은 발행일로부터 지정된 유효 기간 내에만 사용 가능하며, 만료일 이후에는 사용할 수 없습니다.
- 쿠폰은 본인 소지 시에만 사용 가능하며, 타인에게 양도할 수 없습니다.
- 쿠폰은 일회성이며, 재사용이 불가능합니다.
- 쿠폰은 특정 서비스에 한하여 유효합니다. 다른 서비스나 품목에는 사용할 수 없습니다.
- 쿠폰 사용 시, 해당 업장의 운영 상황에 따라 제공 여부가 달라질 수 있습니다. 
- 쿠폰 사용에 관한 문의사항이 있을 경우 MY>문의하기로 문의해 주세요.

**Comment by somedd** [comment]
@Dumbs-app 1.0.1에서 수정완료
