### ISSUE TITLE
[어드민] 2차 어드민 가입 완료 시 '추가 정보 입력하기' 팝업 및 버튼 추가

### ISSUE THREAD

**Issue by 3d3nch01** [Dumbs-app/Dumbs#77]
[현재 문제점]
현재 어드민 가입 시 이메일로 가입 심사 승인하는 구조가 없습니다.

[개선사항]
가입 완료 후 
1. 바로 '추가 정보 입력하기' 버튼이 포함된 팝업 노출
2. 가입 완료 페이지 내 '추가 정보 입력하기' 버튼 추가
3. 가입 완료 페이지 내 문구 수정

추가 정보 입력하기 버튼을 클릭하면 '영업시간 및 입장료' 입력 페이지로 이동합니다.

[기대화면]
https://www.figma.com/design/iUbFvODkxJ79DgXydUUyug/%EB%8D%A4%EC%A6%88?node-id=1482-46753&t=Um849kICywdby3Mt-11

**Comment by Dumbs-app** [comment]
@3d3nch01 
이든님 이거랑 같은 맥락으로
아래 플로우 (가게정보 입력완료 후)에도
'저장하기' 눌렀을때

'확인'버튼만 주지 않고 
'영업시간 입력하러가기' 등 다음플로우로 연결되면 좋을 것 같아요!

영업시간 입력 후에도 마찬가지로 '메뉴 입력하러가기' 등으로 플로우 연결되면 좋을 것 같습니다
확인 부탁드려용!!

![Image](https://github.com/user-attachments/assets/fba0ebad-f31c-4bbb-b641-8554a8071a4c)

**Comment by 3d3nch01** [comment]
@Dumbs-app 홍시님 확인했는데요!

제가 알기론 이게 페이지별로 입력/미입력 상태가 구분되지 않기 때문에
2. 영업시간 3. 메뉴 정보를 입력 완료한 상태에서 -> 1. 기본 정보를 수정하면 항상 '영업시간 입력하러 가기' 버튼이 뜰 거 같거든요!
(영업시간에서 수정할 정보가 없음에도!)

그래서 혹시 말씀주신 방향이
저장하기 누른 뒤
A. '영업시간 입력하러 가기', '확인(닫기)' 버튼이 2가지로 노출되는 걸 말씀하신 건가요?
아니면 
B. '영업시간 입력하러 가기' 버튼 1개만 노출되는 걸 말씀하신 건가요?

**Comment by Dumbs-app** [comment]
@3d3nch01 
네넵 지금 업장 입력 행태를 지켜봤을때는
초기에 1~3까지 정보 셋팅하고나서 다시 1을 고치러가는 플로우는 거의 없을 것 같긴 해서
우선은 1에서 끝나지않고 2->3으로 보내주는 플로우가 더 중요한 상황으로 보여서요!

말씀주신 A안으로 적용되어도 충분할 것 같습니당!!

**Comment by 3d3nch01** [comment]
@Dumbs-app
화긴 화긴! 감사합니당. 
태스크 https://github.com/Dumbs-app/Dumbs_phase2/issues/28#issue-2516549212 로 신설해 두었습니다!
